project:
  type: book

execute:
  freeze: auto

book:
  title: "Percepción de Distancia Aplicada a la Composición Sonora"
  #subtitle: "Auditory Distance Perception and Multisensory Integration"
  author:
  - name: Dr. Ezequiel Abregú
    orcid: 
    email: eabregu@unq.edu.ar
    affiliations:
      - name: CONICET - UNQ
  date: "2018-03-12"

  chapters:
    - index.qmd
    - chapters/01-introduccion.qmd
    - chapters/02-sistema-auditivo.qmd
    - chapters/03-revision-pad.qmd
    - chapters/04-distancia-musica.qmd
    - chapters/05-pvd.qmd
    - chapters/06-multisensorial.qmd
    - chapters/07-rol-pad.qmd
    - chapters/08-metodo-respuesta.qmd
    - chapters/09-contexto-pvd.qmd
    - chapters/10-ciencia-arte.qmd
    - chapters/11-entrevistas.qmd
    - chapters/12-conclusiones.qmd
    - chapters/13-anexos.qmd
  
  page-footer:
    center: 
    - text: "Dr. Ezequiel Abregú"

  reader-mode: true
  #repo-url: https://ridaa.unq.edu.ar/handle/20.500.11807/837
  sidebar: 
    tools:
      - icon: filetype-pdf
        href: https://ridaa.unq.edu.ar/handle/20.500.11807/837
        text: "Download PDF"
  #repo-actions: [issue]

#  sidebar: 
#    #background: "#F5F5F5"
#    logo: /assets/images/index/cover-5.png
#    search: true

bibliography: references.bib

format:
  html:
    mermaid: {}
    theme:
      light: yeti
      dark: slate
    toc: true
    #toc-location: left
    code-copy: true
    code-overflow: wrap
    sidebar: true
    page-layout: full
    lightbox: true

#  pdf:
#    documentclass: scrreprt
#    toc: true
#    number-sections: true

website:
  navbar: false
  page-navigation: true

toc-title: Índice

#reference-location: margin
#citation-location: margin
#caption-location: margin