# Conclusiones finales

Desde un punto de vista general, esta tesis ha tenido como objetivo
principal realizar una investigación multidisciplinaria sobre el estudio
perceptivo del espacio en la música a partir de la información
proveniente de los estudios científicos sobre la naturaleza,
características y percepción de las pistas auditivas y visuales
involucradas en la estimación de distancia. De acuerdo a este objetivo
se desarrolló un plan de trabajo que contempló la realización de una
serie de revisiones sobre la percepción auditiva y visual de distancia,
además de diversos estudios en el campo de la psicoacústica experimental
y, finalmente, la producción de obras de arte en estrecha relación con
la información proveniente del ámbito científico.

Hemos visto que en el ámbito científico, a diferencia de los estudios de
percepción espacial en acimut y elevación, la Percepción Auditiva de
Distancia (PAD) es la que menos atención ha recibido por parte de los
investigadores. Una de las posibles causas de este hecho es que la PAD
involucra una gran cantidad de indicios y variables que dependen tanto
del estímulo sonoro como de las características del contexto visual y
auditivo. En reiteradas ocasiones hemos concluído que la mayoría de las
pistas de PAD son dependientes de algún tipo de referencia (visual y/o
auditiva) o conocimiento previo del contexto para obtener una percepción
espacial coherente y efectiva. Al mismo tiempo, en el Capítulo 3 también
hemos visto casos en los que ciertos indicios (como la relación
directo/reverberante) que pueden modular la PAD sin necesidad de
comparar información proveniente de experiencias previas (llamadas
pistas absolutas).

Como hemos visto, un gran número de estudios de PAD reportan que la
distancia percibida a una fuente sonora es particularmente subestimada
en distancias mayores a 2 metros del oyente (Zahorik, 2005; Kolarik et
al., 2013). Una posible respuesta a este hecho podría estar determinado
por la incidencia de lo que se denomina *horizonte auditivo*
(Bronkhorst, 2002) el cual ocurre cuando el campo acústico reverberante
domina completamente el campo directo. Sin embargo, existe una gran
cantidad de evidencia que demuestra que nuestra percepción de los
indicios, proporcionados por un entorno determinado, depende de la
integración multisensorial. De acuerdo a este hecho, es esperable que la
PAD pueda ser modificada tanto cuantitativa como cualitativamente por la
presencia de información proveniente de otras modalidades.

En el Capítulo 7 se expone un trabajo (Calcagno et al., 2012) donde
mostramos que la presencia de información visual afecta directamente la
PAD, lo cual sostiene la hipótesis de que la información visual brindada
por el contexto puede servir como una referencia de gran impacto a la
hora de estimar la distancia a un objetivo, además de ofrecer
información sobre las dimensiones de la sala en la que se desarrolla el
experimento. Este hecho sugiere que esta información, proveniente de la
modalidad visual, facilita la calibración de la PAD dentro de un espacio
determinado. Por último, es interesante observar que en este estudio se
sugiere que la información brindada por la reverberación del recinto
puede contribuir a conformar una imagen mental bastante clara del tamaño
del recinto y que, por lo tanto, que este hecho puede ayudar a calibrar
las demás pistas asociadas a espacio determinado. De esta manera, en la
línea de investigación sobre la integración multisensorial, estos
resultados representaron un antecedente de gran relevancia y sentaron
las bases para la realización de un estudio sobre cómo la Percepción
Visual de Distancia (PVD) puede ser afectada por el contexto auditivo,
en particular por la información relacionada con la reverberación de un
recinto.

De acuerdo a estos antecedentes, y advirtiendo que el reporte verbal ha
sido el método de respuesta más utilizados en estudios de PAD, se
consideró importante utilizar un enfoque multimodal (involucrando la
modalidad visual y auditiva) para el diseño de un setup experimental que
sirviera para estudiar la eficacia de una metodología de acción directa
para medir la PAD en el campo lejano (llamado *Cross Modal Direct
Location*, o CMDL). Los resultados de este estudio mostraron que,
utilizando la metodología propuesta, las respuestas fueron
significativamente menos sesgadas y menos compresivas en comparación a
otros estudios de PAD que utilizaron como método de respuesta el RV.
Estos resultados mostraron una estrecha correlación con otros tipos de
métodos de acción directa (Brungart et al., 2000; Andre y Rogers, 2006).
Además, los resultados mostraron que esta diferencia entre métodos
podría deberse a los cambios de en la calibración de la respuesta de la
distancia percibida inducida por sistema de medición. En el caso de la
CMDL, la información visual proporcionada por el dispositivo fue el
responsable de la respuesta robusta y precisa en comparación a las RVs,
lo cual sugiere que el RV necesita mayor cantidad de referencia
espaciales del contexto (sobre todo visuales) para calibrar
correctamente la PAD. Diversos estudios (Zahorik, 2001; Calcagno, 2012)
apoyan este hecho mostrando que las respuestas de RVs fueron más
eficientes y precisas ante la presencia de múltiples pistas del contexto
visual. Por este motivo, uso del método CMDL pudo haber mejorado la
calibración de la PAD debido a que los participantes no necesitaron
realizar una transformación mental a una medida en metros referente a la
ubicación del objetivo, representando un método interesante y confiable
para medir la PAD.

En la misma línea de los estudios multimodales mencionados, los
resultados del trabajo expuesto en el Capítulo 9 mostraron que, ante la
falta de señales visuales que den información del entorno, el contexto
auditivo afectó de forma contundente la PVD, además de que la sala
reverberante se percibió significativamente de mayores dimensiones que
la cámara anecoica. En concordancia a este hecho, los sujetos ubicados
en la cámara reverberante percibieron todos los objetivos visuales más
alejados que en la cámara anecoica. Esto parece indicar que el contexto
auditivo afectó la PVD debido a la información proveniente de la
reverberación, la cual estuvo asociada directamente con la percepción
del tamaño del recinto en el cual se desarrolló el experimento. Además
de apoyar esta hipótesis, los resultados son concordantes con otros
estudios relacionados a la estimación del tamaño en relación al nivel de
reverberación de un recinto (Kolarik et al., 2013; Cabrera et al., 2005)
y presentan una correlación positiva entre la distancia más lejana
reportada por los participantes y la estimación del tamaño del recinto
en función de la información ofrecida por la reverberación. Este hecho
podría deberse a que ante la falta de información visual del entorno,
los sujetos debieron utilizar información proveniente de la modalidad
auditiva para crear una representación mental del tamaño del recinto, lo
cual incidió directamente en las respuesta de estimación de distancia al
objetivo visual.

En otro ámbito, hemos visto que en el panorama musical actual el espacio
sonoro puede representar una importante elemento estructural en el
discurso y que, para construir una espacialidad convincente, es
necesario contemplar tanto aspectos artísticos como perceptivos. En el
caso particular de la PAD, hemos visto que involucra una variedad de
indicios acústicos y no-acústicos, los cuales pueden afectar de manera
contundente el manejo del espacio en la música. Sin embargo, a pesar de
que el uso consciente del espacio en la música cuenta con varias décadas
de desarrollo, el manejo del plano de la distancia dista mucho de estar
resuelto. Advirtiendo este hecho, uno de los principales objetivos de
esta tesis hizo foco en abordar esta problemática desde una perspectiva
artística y multidisciplinaria, lo cual representó un trabajo sin
referentes a nivel local. Es interesante observar que cada una de las
obras expuestas en el Capítulo 10 tuvieron como eje principal del
proceso creativo a la información proveniente del ámbito científico
respecto al estudio de la PAD. Esto no sólo representó un eje común y
estructural para la realización de la serie de obras analizadas, sino
que también pudo constatarse la posible aplicación de las técnicas
compositivas en distintos ámbitos y dispositivos de difusión (ensamble
instrumental, obra escénica-performática, instalación sonora, escultura
sonora). En el caso particular de las piezas instrumentales
"*Instrucciones para el contacto con mundo suprafísicos*" y "*Los
océanos tiene oídos*", adoptar como herramientas compositivas las
características del ancho de banda espectral en la PAD utilizando
instrumentos acústicos representó en sí mismo un problema ya que, como
vimos, no es sencillo manipular de manera aislada los indicios
involucrados utilizando instrumentos acústicos. Además, en una situación
de concierto con público, a esta problemática se le suma el hecho de que
la información visual (del entorno y de la ubicación de la fuente)
podría atentar contra la intención de generar distintos planos y
trayectorias en distancia. Sin embargo, el enfoque utilizado para la
composición de las piezas instrumentales representó un marco de
referencia decisivo para desarrollar cada elemento de la textura, con
características espectrales bien definidas, utilizando un conjunto de
técnicas extendidas instrumentales específicas, lo cual acentuó la
intención de situar cada plano de la textura en un lugar bien definido
en distancia. Por otro lado, debemos tener en cuenta que la traslación
literal de la información proveniente del ámbito científico respecto al
ancho de banda espectral en la PAD podría no ser efectiva en todos los
casos. Esto se debe a que, a pesar de ser robustos, los resultados
experimentales suelen ser dependientes de las características acústicas
de la sala. Sin embargo, en una situación de reproducción de música
grabada, a través de parlantes, la incidencia del entorno podría ser
minimizada.

Por otra parte, un caso interesante se da en la instalación *Búcaro de
Secretos*, la cual tuvo una fuerte correlación con un estudio de
Philbeck y Mershon (2002) [en donde el tipo de espacialización utilizada
y la construcción del espacio sonoro en distancia no se centró en el
tipo de sistema de espacialización utilizado, sino que se optó por
generar un espacio virtual a partir de la experiencia y conocimiento
previo de las fuentes sonoras (en este caso, mediante la utilización de
voces humanas). Esto podría representar un cambio de paradigma en cuanto
construcción de la espacialidad de una obra ya que, en el caso de
*Búcaro de Secretos*, el espacio sonoro y los distintos planos generados
en distancia poseen bastante independencia de la tecnología de
reproducción, lo cual abre las puertas a un interesante campo de
investigación a futuro.]

[Un caso paradigmático de cómo la percepción de distancia puede
estructurar el diseño del espacio sonoro y de la acción performática se
da en la obra LEJOS, en donde se pusieron en juego los conceptos de
composición multi-capa en distancia y el de Perspectiva Acústica. En
esta obra se implementaron soluciones técnicas y discursivas que
respondieron no sólo a necesidades artísticas sino también a la
aplicación práctica de información proveniente de estudios perceptivos.
De acuerdo esto, fue fundamental conocer de qué manera un ambiente
determinado (en este caso, la sala de teatro) contribuía o contradecía
la construcción de distintos planos en distancia. Advirtiendo este
hecho, resultó efectivo realizar un proceso de expansión sonora de las
características acústicas de la sala, en donde convivieron señales
reales y virtuales para conformar un espacio sonoro (híbrido) y
performático unificado. Un aspecto interesante del proceso de aplicación
del marco teórico utilizado en una obra escénica fue no dejar de lado el
criterio e imaginario empírico para evaluar la efectividad de las
técnicas empleadas para el manejo del espacio sonoro. De acuerdo a esta
idea, en muchos casos se apeló a forzar los diseños y sistemas empleados
para ampliar y exagerar aún más el efecto deseado. Como ejemplos de lo
antedicho podemos mencionar, entre otros: la ampliación del rango
dinámico en un ámbito entre lo sutil y lo estruendoso, el diseño no
uniforme (no geométrico) del sistema de espacialización de parlantes, la
amplificación y distribución de los sonidos producidos en escena,
utilización de parlantes de distintos tamaños y el refuerzo de sonido.
Esta interesante problemática artística resultó muy efectiva, la cual
estuvo en correlación directa con métodos muy difundidos en distintas
obras escénicas, en donde el diseño del espacio de acción y performático
responden a criterios sobre cómo el espectador percibe el espacio que el
artista le propone.]

[Como hemos visto en la mayoría de los casos, para que sean efectivos,
los estudios perceptivos de distancia se han desarrollaron en entornos
diseñados y modificados a tal fin, situación que difiere ampliamente con
lo que ocurre en espacios destinados a la producción sonora y la
exhibición de obras de arte. Esto quedó reflejado en el Capítulo 11, en
donde los entrevistados manifestaron de forma unánime la equivalente
importancia que tienen tanto las intenciones artísticas como la
percepción del oyente, siendo esto último lo que finalmente importa.
Dado este hecho, la aplicación de la información proveniente de los
estudios perceptivos podría estar sujeta a adaptar el entorno en donde
transcurre la obra o bien adaptar el planteo espacial de la obra al
contexto. En primer lugar, modificar o controlar la información del
entorno para que la percepción de los indicios de distancia sean
coherentes y eficaces. En segundo lugar, utilizar un entorno híbrido
(real y virtual) que sea lo suficientemente flexible como para que el
entorno no atente contra el manejo del espacio sonoro que se quiera
implementar.]

[Los resultados obtenidos en este trabajo sugieren conclusiones con
múltiples perspectivas y un marco de referencia novedoso en cuanto a la
utilización del espacio en un contexto artístico. La revisión de los
avances en el ámbito científico y la información adquirida en el
desarrollo de este trabajo contribuyen a una manera efectiva de utilizar
un marco teórico de referencia que pueda adquirir una resignificación
con fines creativos y que el artista pueda hacer uso del mismo para
interactuar e intervenir en el proceso de realización de una obra. Por
otro lado, el enfoque abordado en esta tesis puede resultar de gran
utilidad a la hora de aplicar nuevos criterios de análisis, tanto
discursivos como taxonómicos, más abarcativos respecto al uso del
espacio, contemplando no sólo el aspecto sonoro sino también el aporte
que proporcionan otros factores no sonoros.]

Finalmente, además de conformar una contundente fuente de información
de aplicación en el ámbito artístico, los resultados obtenidos en esta
tesis representaron un importante aporte en el campo de psicofísica
experimental a nivel local e internacional. Prueba de ello son las seis
publicaciones, con referato, en distintas revistas especializadas en
mecanismos fisiológicos y perceptivos. Dado este hecho, el trabajo
realizado en esta tesis representa una investigación multidisciplinaria
pionera en Argentina, contribuyendo al conocimiento científico sobre la
Percepción Visual y Auditiva de Distancia, integrando aspectos
psicofísicos, biológicos y artísticos. Además de aportar información
fundamental para el área de estudio, los resultados obtenidos podrían
ayudar a delimitar la interrelación de factores cognitivos y
perceptuales subyacentes.

## Referencias bibliográficas

Andre, J. y Rogers, S. Using verbal and blind-walking distance estimates
to investigate the two visual systems hypothesis. Attention, Perception,
y Psychophysics 68(3), 353-361 (2006).

Bronkhorst, A. W. y Houtgast, T. Auditory distance perception in rooms.
Nature, 397, 517-520 (1999).

Brungart, D. S., Rabinowitz, W. M., y Durlach, N. I. Evaluation of
response methods for the localization of nearby objects. Attention,
Perception, y Psychophysics 62(1), 48-65. (2000).

Cabrera, D., Jeong, D., Kwak, H. J., Kim, J. Y. y Duckjin-gu, J. (2005,
July). Auditory room size perception for modeled and measured rooms. In
*Internoise, the 2005 Congress and Exposition on Noise Control
Engineering*, Rio de Janeiro, Brazil, 7-10 August 2005.

Calcagno, E. R., Abregú, E. L., Eguía, M. C. y Vergara, R. The role of
vision in auditory distance perception. Perception 41(2), 175-192
(2012).

Calcagno, E. R., Abregú, E. L., Eguía, M. C., y Vergara, R. (2012). The
role of vision in auditory distance perception. Perception 41(2),
175-192 (2001).

Kolarik, A. J., Pardhan, S., Cirstea, S. y Moore, B. C. Using acoustic
information to perceive room size: effects of blindness, room
reverberation time, and stimulus. *Perception*, **42**(9), 985-990
(2013).

Philbeck, J. W. y Mershon, D. H. Knowledge About Typical Source Output
Influences Perceived Auditory Distance. Journal of the Acoustical
Society of America 111, 1980-83 (2002):

Zahorik, P. Auditory display of sound source distance. Proceedings of
the 8th International Conference on Auditory. Kyoto, Japan, 239--243
(1999).

Zahorik, P. Estimating sound source distance with and without vision.
Optometry y Vision Science, 78(5), 270-275 (2001).

Zahorik, P., Brungart, D. S. y Bronkhorst, A. W. Auditory Distance
Perception in Humans: A Summary of Past and Present Research. Acta
Acustica united with Acustica, 91, 409-420 (2005).

